apiVersion: v1
kind: Service
metadata:
  name: cacheapi
  labels:
    app: cacheapi
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: cacheapi
    tier: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cacheapi
  labels:
    app: cacheapi
spec:
  selector:
    matchLabels:
      app: cacheapi
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: cacheapi
        tier: frontend
    spec:
      containers:
      - name: cacheapi
        image: docker.io/migutak/cacheapi:1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5500

